In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [63]:
names=['Class','value1','value2','value3','value4','value5','value6','value7','value8','value9','value10','value11','value12','value13','value14','value15','value16']

In [64]:

dataset = pd.read_csv('literki.data',usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],names=names,header=None)


In [66]:
#checking values from file 
dataset.head(10)

Class  value1  value2  value3  value4  value5  value6  value7  value8  \
0     S       4      11       5       8       3       8       8       6   
1     A       1       1       3       2       1       8       2       2   
2     J       2       2       4       4       2      10       6       2   
3     M      11      15      13       9       7      13       2       6   
4     M       6       9       8       6       9       7       8       6   
5     C       7      10       5       5       2       6       8       6   
6     J       2       2       3       3       1      10       6       3   
7     J       1       3       2       2       1       8       8       2   
8     H       4       5       5       4       4       7       7       6   
9     S       3       2       3       3       2       8       8       7   

   value9  value10  value11  value12  value13  value14  value15  value16  
0       9        5        6        6        0        8        9        7  
1       2        8        2        8        1        6        2        7  
2       6       12        4        8        1        6        1        7  
3       2       12        1        9        8        1        1        8  
4       5        7        5        8        8        9        8        6  
5       8       11        7       11        2        8        5        9  
6       6       12        4        9        0        7        1        7  
7       5       14        5        8        0        7        0        7  
8       6        7        6        8        3        8        3        8  
9       5        7        5        7        2        8        9        8

In [130]:
X = dataset.iloc[:,1:].values #contains all values 
y = dataset.iloc[:,0].values #Contains first column

In [131]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 
#Creating test and Training environment



In [132]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

D:\Users\Karol Mierzwa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Users\Karol Mierzwa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Users\Karol Mierzwa\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [133]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(X_train, y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [134]:
y_pred = classifier.predict(X_test)  

In [135]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[156   2   0   0   0   0   2   0   1   0]
 [  0 148   4   0   0   0   0   0   1   0]
 [  0   3 138   2   1   0   0   0   1   4]
 [  0   1   0 149   0   2   0   0   1   1]
 [  0   0   0   1 138   1   0   0   2   0]
 [  0   0   2   1   0 131   0   0   1   0]
 [  0   0   0   0   0   0 148   0   1   0]
 [  0   0   2   0   0   0   0 142   1   1]
 [  0   0   0   1   0   0   0   0 178   0]
 [  0   0   2   0   0   0   0   1   0 154]]
              precision    recall  f1-score   support

           A       1.00      0.97      0.98       161
           C       0.96      0.97      0.96       153
           E       0.93      0.93      0.93       149
           H       0.97      0.97      0.97       154
           J       0.99      0.97      0.98       142
           L       0.98      0.97      0.97       135
           M       0.99      0.99      0.99       149
           S       0.99      0.97      0.98       146
           U       0.95      0.99      0.97       179
           Z       0.96     